=== gpe-mw-training/camel-labs/6_EIP_Patterns/camel-aggregator/src/main/resources/xsd/Payment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="xmlns:tns=http://training.gpe.redhat.com/payment" elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://training.gpe.redhat.com/payment">

    <element name="Payment">
    	<complexType>
    		<sequence>
    			<element name="from" type="string"></element>
    			<element name="to" type="string"></element>
    			<element name="amount" type="float"></element>
    		</sequence>
    	</complexType>
    </element>
    
    <element name="Payments">
    	<complexType>
    		<sequence>
    			<element name="Currency" type="string"/>
    			<element ref="tns:Payment" minOccurs="0" maxOccurs="unbounded"/>
    		</sequence>
    	</complexType>    	
    </element>
    
</schema>

=== gpe-mw-training/camel-labs/6_EIP_Patterns/camel-aggregator/src/main/data/in/USPayments.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Payments xmlns:tns="http://training.gpte.redhat.com/payment"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="training.gpte.redhat.com/payment ../../resources/xsd/Payment.xsd">

    <tns:Currency>USD</tns:Currency>

    <tns:Payment>
        <tns:from>chad-USD</tns:from>
        <tns:to>jeff</tns:to>
        <tns:amount>1000000.0</tns:amount>
    </tns:Payment>
    <tns:Payment>
        <tns:from>rachel-USD</tns:from>
        <tns:to>chad</tns:to>
        <tns:amount>78.0</tns:amount>
    </tns:Payment>
    <tns:Payment>
        <tns:from>rachel-USD</tns:from>
        <tns:to>chad</tns:to>
        <tns:amount>13.0</tns:amount>
    </tns:Payment>
    <tns:Payment>
        <tns:from>jingjing-USD</tns:from>
        <tns:to>jeff</tns:to>
        <tns:amount>10.0</tns:amount>
    </tns:Payment>

</tns:Payments>

=== gpe-mw-training/camel-labs/6_EIP_Patterns/camel-aggregator/src/main/data/in/EUPayments.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Payments xmlns:tns="http://training.gpte.redhat.com/payment"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="training.gpte.redhat.com/payment ../../resources/xsd/Payment.xsd">

    <tns:Currency>EUR</tns:Currency>

    <tns:Payment>
        <tns:from>chad-EUR</tns:from>
        <tns:to>jeff</tns:to>
        <tns:amount>1000000.0</tns:amount>
    </tns:Payment>
    <tns:Payment>
        <tns:from>jeff-EUR</tns:from>
        <tns:to>chad</tns:to>
        <tns:amount>20.0</tns:amount>
    </tns:Payment>
    <tns:Payment>
        <tns:from>bernard-EUR</tns:from>
        <tns:to>chad</tns:to>
        <tns:amount>42.0</tns:amount>
    </tns:Payment>
    <tns:Payment>
        <tns:from>hong-EUR</tns:from>
        <tns:to>jeff</tns:to>
        <tns:amount>12345.0</tns:amount>
    </tns:Payment>

</tns:Payments>
